# Generated by Django 4.2.6 on 2024-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
