# Generated by Django 4.2.6 on 2024-04-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipe_cooking_time"),
        ("favorite", "0002_alter_favorite_author_alter_favorite_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite",
                to="recipes.recipe",
            ),
        ),
    ]
